### ISSUE TITLE
Moving between windows visiting same buffer

### ISSUE THREAD

**Issue by aurajamming** [lukhas/buffer-move#11]
I frequently split my buffers to view one section of a file while editing another. If I try to use buffer-move to swap the contents of two windows visiting the same buffer, position information for one of them is lost - both windows end up looking at the same point in the buffer, and my previous views are lost.

**Comment by joca-bt** [comment]
If this could be fixed it would be awesome. I also need this use case.

**Comment by joca-bt** [comment]
I've fixed this, I'll submit a pull request when I get some time.

**Comment by joca-bt** [comment]
I've fixed this, please have a look at pull request #14.

**Comment by jcs090218** [comment]
@lukhas Any chance to merge the PR #14?

**Comment by lukhas** [comment]
Indeed, merged.
