### ISSUE TITLE
No more checking the neighbourhood

### ISSUE THREAD

**Issue by geyslan** [lukhas/buffer-move#6]
The [merge](https://github.com/lukhas/buffer-move/commit/7ed34773350e0b94db05e830b1a9989c4481f56b) ripped off the dedicated window and minibuffer checking. My windows are swapping crazily again. Could you revert it?.

**Comment by geyslan** [comment]
@lukhas Are you alive?

**Comment by lukhas** [comment]
I am, I missed your previous comment.

**Comment by lukhas** [comment]
Commit reverted, better?

I should point out that I experienced no weird behavior with this patch active.

**Comment by geyslan** [comment]
@lukhas no problem. =)

Well, it didn't work because the problem is in the lack of dedicated window checking:

-      (if (window-dedicated-p other-win)
-	  (error "The window under this one is dedicated"))

My patch included that:
https://github.com/lukhas/buffer-move/commit/0f626101c54a1a1dddecefbe02b62394082708b6

But the merge ripped it off.

**Comment by lukhas** [comment]
Ok I get it, commit 19dd833cdecc58b572b269cf26dc1b2f325f2034 broke stuff (and I reverted the wrong commit earlier).

I'm a bit rusty on lisp and git today, I think it'd be faster if you re-patched it on your side and then sent me a pull request, this time I'll try my best not to break it :)

**Comment by geyslan** [comment]
Ok then.

Later I'll patch it. o/

2015-05-22 12:14 GMT-03:00 lukhas <notifications@github.com>:

> Ok I get it, commit 19dd833
> <https://github.com/lukhas/buffer-move/commit/19dd833cdecc58b572b269cf26dc1b2f325f2034>
> broke stuff (and I reverted the wrong commit earlier).
>
> I'm a bit rusty on lisp and git today, I think it'd be faster if you
> re-patched it on your side and then sent me a pull request, this time I'll
> try my best not to break it :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lukhas/buffer-move/issues/6#issuecomment-104686219>.
>



-- 
Regards,

Geyslan G. Bem
hackingbits.com

**Comment by geyslan** [comment]
Done.
https://github.com/lukhas/buffer-move/pull/7

o/

**Comment by lukhas** [comment]
Merged.

**Comment by geyslan** [comment]
@lukhas Please release a new version (github) for the package managers see the changes.

**Comment by lukhas** [comment]
Good point, done.

**Comment by geyslan** [comment]
Cheers 0.6.2.
